  METHOD get_ledger_datas.
*    TYPES: BEGIN OF lty_cash_sel,
*             comp_code      TYPE bukrs,
*             cajo_number    TYPE c LENGTH 4,
*             posting_number TYPE belnr_d,
*           END OF lty_cash_sel.

    TYPES: BEGIN OF ty_blart,
             blart   TYPE zetr_t_hbbtr-blart,
             hkon1   TYPE zetr_t_hbbtr-hkon1,
             hflg1   TYPE c LENGTH 1,
             hkon2   TYPE zetr_t_hbbtr-hkon2,
             hflg2   TYPE c LENGTH 1,
             hkon3   TYPE zetr_t_hbbtr-hkon3,
             hflg3   TYPE c LENGTH 1,
             hkon4   TYPE zetr_t_hbbtr-hkon4,
             hflg4   TYPE c LENGTH 1,
             blart_t TYPE zetr_t_defky-blart_t,
             gbtur   TYPE zetr_t_defky-gbtur,
             oturu   TYPE zetr_t_defky-oturu,
             chcok   TYPE c LENGTH 1,
           END OF ty_blart.

    TYPES: BEGIN OF ty_colitem,
             bukrs TYPE bukrs,
             belnr TYPE belnr_d,
             gjahr TYPE gjahr,
             buzei TYPE buzei,
             docln TYPE c LENGTH 6,
             cldoc TYPE zetr_e_descr255,
           END OF ty_colitem.

    TYPES : BEGIN OF ty_bkpf ,
              bukrs TYPE bukrs,
              belnr TYPE belnr_d,
              gjahr TYPE gjahr,
              blart TYPE blart,
              awtyp TYPE c LENGTH 5,
              awkey TYPE c LENGTH 20,
              stblg TYPE belnr_d,
              xblnr TYPE xblnr1,
              bstat TYPE zetr_e_bstat,
              tcode TYPE tcode,
              bktxt TYPE bktxt,
              budat TYPE budat,
              bldat TYPE bldat,
              rldnr TYPE fins_ledger,
            END OF ty_bkpf.

    TYPES : BEGIN OF ty_bseg ,
              bukrs TYPE bukrs,
              hkont TYPE hkont,
              gjahr TYPE gjahr,
              buzei TYPE buzei,
              gsber TYPE gsber,
              lokkt TYPE c LENGTH 10,
              belnr TYPE belnr_d,
              docln TYPE c LENGTH 6,
              budat TYPE budat,
              bldat TYPE bldat,
              rhcur TYPE waers,
              blart TYPE blart,
              drcrk TYPE shkzg,
              mwskz TYPE mwskz,
              hsl   TYPE zetr_e_edf_dmbtr,
              lifnr TYPE lifnr,
              kunnr TYPE lifnr,
              koart TYPE koart,
              sgtxt TYPE sgtxt,
              shkzg TYPE c LENGTH 1,
              dmbtr TYPE zetr_e_edf_dmbtr,
              posn2 TYPE n LENGTH 6,
              xcpdd TYPE c LENGTH 1,
              wrbtr TYPE zetr_e_edf_dmbtr,
              dmbe3 TYPE zetr_e_edf_dmbtr,
              dmbe2 TYPE zetr_e_edf_dmbtr,
              waers TYPE waers,
            END OF ty_bseg.

    TYPES : BEGIN OF ty_bsec,
              bukrs TYPE bukrs,
              belnr TYPE belnr_d,
              gjahr TYPE gjahr,
              buzei TYPE buzei,
              name1 TYPE name1_gp,
              name2 TYPE name1_gp,
              name3 TYPE name1_gp,
              name4 TYPE name1_gp,
            END OF ty_bsec.

    TYPES : BEGIN OF ty_bsed,
              bukrs TYPE bukrs,
              belnr TYPE belnr_d,
              gjahr TYPE gjahr,
              buzei TYPE buzei,
              boeno TYPE c LENGTH 10,

            END OF ty_bsed.

    TYPES : BEGIN OF ty_kna1 ,
              kunnr TYPE lifnr,
              name1 TYPE name1_gp,
              name2 TYPE name1_gp,
            END OF ty_kna1.


    TYPES : BEGIN OF ty_lfa1 ,
              lifnr TYPE lifnr,
              name1 TYPE name1_gp,
              name2 TYPE name1_gp,
            END OF ty_lfa1.


    TYPES: BEGIN OF ty_gsber,
             sign   TYPE c LENGTH 1,
             option TYPE c LENGTH 2,
             low    TYPE gsber,
             high   TYPE gsber,
           END OF ty_gsber.

    TYPES: BEGIN OF ty_hkont,
             sign   TYPE c LENGTH 1,
             option TYPE c LENGTH 2,
             low    TYPE hkont,
             high   TYPE hkont,
           END OF ty_hkont.

    TYPES: BEGIN OF ty_dybel,
             bukrs TYPE bukrs,
             belnr TYPE belnr_d,
             gjahr TYPE gjahr,
           END OF ty_dybel.

    TYPES: BEGIN OF ty_blryb,
             bukrs TYPE bukrs,
             blart TYPE blart,
           END OF ty_blryb.

    DATA: lv_cursor          TYPE cursor,
          lt_bkpf            TYPE SORTED TABLE OF ty_bkpf WITH UNIQUE KEY bukrs belnr gjahr bstat awtyp,
          lt_bkpf_send       TYPE TABLE OF ty_bkpf,
*          lt_cash_sel        TYPE TABLE OF lty_cash_sel,
*          lt_cash_data       TYPE SORTED TABLE OF tcj_positions WITH UNIQUE KEY comp_code cajo_number posting_number transact_number,
*          lt_cash_post       TYPE SORTED TABLE OF tcj_positions WITH NON-UNIQUE KEY comp_code cajo_number posting_number,
          lt_bkpf_add        TYPE TABLE OF ty_bkpf,
          lt_bkpf_tmp        TYPE TABLE OF ty_bkpf,
          lt_bseg            TYPE SORTED TABLE OF ty_bseg WITH NON-UNIQUE KEY bukrs belnr gjahr buzei hkont lokkt gsber kunnr lifnr,
          ls_bseg            LIKE LINE OF lt_bseg,
          lt_bseg_tmp        TYPE TABLE OF ty_bseg,
          lt_bseg_dat        TYPE TABLE OF ty_bseg,
          lt_colitm          TYPE SORTED TABLE OF ty_colitem WITH UNIQUE KEY bukrs belnr gjahr buzei docln,
          lt_colitm_bseg     TYPE SORTED TABLE OF ty_colitem WITH UNIQUE KEY bukrs belnr gjahr,
          ls_colitm          LIKE LINE OF lt_colitm,
          lt_bsec            TYPE SORTED TABLE OF ty_bsec WITH UNIQUE KEY bukrs belnr gjahr buzei,
          lt_bsed            TYPE SORTED TABLE OF ty_bsed WITH UNIQUE KEY bukrs belnr gjahr buzei,
*          lt_payr            TYPE SORTED TABLE OF ty_payr WITH NON-UNIQUE KEY zbukr vblnr gjahr,
          lt_bsec_sel        LIKE lt_bseg,
*          lt_faglflexa       TYPE SORTED TABLE OF faglflexa WITH NON-UNIQUE KEY rbukrs docnr ryear buzei docln,
          lt_ledger          TYPE TABLE OF zetr_t_defky,
          lt_skb1            TYPE TABLE OF ty_skb1,
          lc_root            TYPE REF TO cx_root,
          lt_kna1_tmp        TYPE TABLE OF ty_kna1,
          lt_lfa1_tmp        TYPE TABLE OF ty_kna1,
          lt_kna1            TYPE SORTED TABLE OF ty_kna1 WITH NON-UNIQUE KEY kunnr,
          lt_lfa1            TYPE SORTED TABLE OF ty_kna1 WITH NON-UNIQUE KEY kunnr,
          lt_wrong_types     TYPE SORTED TABLE OF zetr_t_bthbl  WITH UNIQUE KEY bukrs belnr gjahr,
          lt_wrong_types_tmp TYPE TABLE OF zetr_t_bthbl,
          lt_copy_belnr      TYPE SORTED TABLE OF zetr_t_blryb WITH UNIQUE KEY blart,
          lt_copy_belnr_tmp  TYPE TABLE OF zetr_t_blryb,
          lt_ex_docs         TYPE SORTED TABLE OF zetr_t_dybel WITH UNIQUE KEY belnr gjahr,
          lt_ex_docs_tmp     TYPE TABLE OF zetr_t_dybel,
          lt_cash            TYPE SORTED TABLE OF zetr_t_ksbel WITH UNIQUE KEY blart tisno,
          lt_cash_tmp        TYPE TABLE OF zetr_t_ksbel,
          lt_cash_temp       TYPE SORTED TABLE OF zetr_t_ksbel WITH NON-UNIQUE KEY blart,
          lv_stblg           TYPE belnr_d,
          lv_stjah           TYPE gjahr,
          lv_awkey           TYPE c LENGTH 20,
          lv_satici          TYPE c LENGTH 1,
          lv_anahesap        TYPE c LENGTH 1,
          lv_count           TYPE i,
          lt_blart           TYPE SORTED TABLE OF zetr_t_hbbtr WITH NON-UNIQUE KEY blart,
          lt_hbbtr           TYPE TABLE OF zetr_t_hbbtr,
          lt_blart_tmp       TYPE SORTED TABLE OF ty_blart WITH NON-UNIQUE KEY blart,
          lt_blart_temp      LIKE gt_blart,
          lv_count_th        TYPE i,
          lv_count_fh        TYPE i,
          lv_skip            TYPE c LENGTH 1,
          lv_hkont           TYPE saknr,
          lv_bktxt           TYPE zetr_e_descr255,
          lv_45day           TYPE i,
          lv_char            TYPE c LENGTH 1000,
          lv_changed         TYPE c LENGTH 1,
          lv_subrc           TYPE sy-subrc,
          lv_count_send      TYPE i,
          lv_taskname        TYPE c LENGTH 20,
          lv_taskcount       TYPE n LENGTH 2,
          lr_hkont           TYPE RANGE OF hkont.

    FIELD-SYMBOLS <fs_bseg> TYPE ty_bseg.

  ENDMETHOD.